[package]
name = "inkframe-android"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "inkframe_engine"
crate-type = ["cdylib", "rlib"]

[dependencies]
inkframe-core.workspace = true
inkframe-engine.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
ash = "0.38.0"
jni = "0.22.4"
ndk-sys = { version = "0.6.0", features = ["nativewindow"] }
